sudo: required
dist: xenial
language: python
git:
  depth: 10
  quiet: true
python:
  - "3.6"
env:
  global:
    - CODECOV_TOKEN="0d2c482b-f42c-4d4c-b092-cb628ad20857"
    - BAZEL_VERSION=0.20.0
    - COVERAGE_PROCESS_START=$PWD/.coveragerc
    - NODE_TOTAL=4  # Total machines running per test setting
  matrix:
    # We test against recent versions of TensorFlow and tf-nightly.

    - TF_VERSION="tf-nightly" NODE_INDEX=0
    - TF_VERSION="tf-nightly" NODE_INDEX=1
    - TF_VERSION="tf-nightly" NODE_INDEX=2
    - TF_VERSION="tf-nightly" NODE_INDEX=3
    - TF_VERSION="2.1" NODE_INDEX=0
    - TF_VERSION="2.1" NODE_INDEX=1
    - TF_VERSION="2.1" NODE_INDEX=2
    - TF_VERSION="2.1" NODE_INDEX=3

matrix:
  allow_failures:
    - python: "3.6"
      env: TF_VERSION="tf-nightly" NODE_INDEX=0
    - python: "3.6"
      env: TF_VERSION="tf-nightly" NODE_INDEX=1
    - python: "3.6"
      env: TF_VERSION="tf-nightly" NODE_INDEX=2
    - python: "3.6"
      env: TF_VERSION="tf-nightly" NODE_INDEX=3

before_install:
  - sudo apt-get -y install pkg-config zip g++ zlib1g-dev unzip
  - wget https://github.com/bazelbuild/bazel/releases/download/"$BAZEL_VERSION"/bazel-"$BAZEL_VERSION"-installer-linux-x86_64.sh
  - chmod +x bazel-"$BAZEL_VERSION"-installer-linux-x86_64.sh
  - ./bazel-"$BAZEL_VERSION"-installer-linux-x86_64.sh --user
addons:
  apt:
    update: true
install:
  - pip install -r requirements.txt
  - pip install numpy --upgrade
  - pip install coverage-enable-subprocess
  - ./oss_scripts/oss_pip_install.sh
script:
  - NOSE_EXCLUDE='.*workers.*|.*nasnet.*.py' nosetests
  - cat /tmp/absl_testing/**/*.txt || true  # Don't error if file does not exist.
after_success:
  # Install codecov for tracking coverage over time.
  - pip install codecov
  - codecov
